export const products = [
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
      id: '2',
      name: 'Tên SP 2',
      createdDate: 'Số lượng đầu kỳ 2',
      createdDate2: 'Số lượng đầu kỳ 3',
      quantityIn: 'Số lượng nhập trong kỳ 2',
      quantityOut: 'Số lượng xuất trong kỳ 2',
      remaining: 'Số lượng còn lại 2',
      costPrice: 'Giá vốn 2',
      totalMoney: 'Thành tiền 2',
      salePrice: 'Giá bán 2',
      totalSale: 'Tổng tiền bán 2',
      warehouse: 'Kho 2'
    },
    
];