export const products = [
    {
      id: '1',
      name: 'Hãng Sản Xuất 1',
      chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-01-01',
      idKH: 'id',
      nameKH: 'ádf',
      tongtien:'1000',
      note:'Hóa đơn',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '2',
      name: 'Hãng Sản Xuất 2',
            chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-02-01',
      idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '3',
      name: 'Hãng Sản Xuất 3',
            chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
      idKH: 'id',
      nameKH: 'naame',
      tongtien:'1000',
      note:'Hóa đơn',
      note:'Hóa đơn',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'nasấme',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },

      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      {
        id: '3',
        name: 'Hãng Sản Xuất 3',
              chinhanh:'368 Tôn Đản',
      kho:'368 Tôn Đản',
      createdDate: '2022-03-01',
        idKH: 'id',
      nameKH: 'name',
      tongtien:'1000',
      note:'Hóa đơn',
        isKey: true,
        dataAlign: 'center',
        dataSort: true
      },
      
];