export const products = [
    {
      id: '1',
      name: 'Tên SP',
      createdDate: 'Số lượng đầu kỳ',
      createdDate2: 'Số lượng đầu kỳ 2',
      quantityIn: 'Số lượng nhập trong kỳ',
      quantityOut: 'Số lượng xuất trong kỳ',
      remaining: 'Số lượng còn lại',
      costPrice: 'Giá vốn',
      totalMoney: 'Thành tiền',
      salePrice: 'Giá bán',
      totalSale: 'Tổng tiền bán',
      warehouse: 'Kho'
    },
    {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      {
        id: '1',
        name: 'Tên SP',
        createdDate: 'Số lượng đầu kỳ',
        createdDate2: 'Số lượng đầu kỳ 2',
        quantityIn: 'Số lượng nhập trong kỳ',
        quantityOut: 'Số lượng xuất trong kỳ',
        remaining: 'Số lượng còn lại',
        costPrice: 'Giá vốn',
        totalMoney: 'Thành tiền',
        salePrice: 'Giá bán',
        totalSale: 'Tổng tiền bán',
        warehouse: 'Kho'
      },
      
];
