export const products = [
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '3',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },
    {
      id: '1',
      name: 'Sản phẩm 1',
      namePhanLoai: 'Tên Phân Loại',
      gia1: 'Giá 1',
      donVi1: 'Đơn Vị 1',
      gia2: 'Giá 2',
      donVi2: 'Đơn Vị 2',
      gia3: 'Giá 3',
      donVi3: 'Đơn Vị 3',
      gia4: 'Giá 4',
      donVi4: 'Đơn Vị 4',
      diem: 'Điểm',
      soNgay: 'Số Ngày',
      hanSuDung: 'Hạn Sử Dụng',
      maVach: 'Mã Vạch',
      maQR: 'Mã QR',
      note: 'Ghi Chú',
      createdDate: 'Ngày Tạo',
      isKey: true,
      dataAlign: 'center',
      dataSort: true
    },

    
];